/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cig.restca.view;

import com.cig.restca.controller.RESTClientController;
import com.cig.restca.model.RESTClientResponse;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Stack;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingWorker;

/**
 *
 * @author User
 */
public class RESTClientFrame extends javax.swing.JFrame {

    private final RESTClientController clientController;
    private RESTClientResponse currentModel;
    private Stack<String> dataStack;
    private String currentData;

    /**
     * Creates new form RESTClientFrame
     *
     * @param clientController
     */
    public RESTClientFrame(RESTClientController clientController) {
        this.clientController = clientController;

        initComponents();
    }
    
    public void addResponse(RESTClientResponse model) {
        final ResponsePanel panel = new ResponsePanel(model, clientController);
        
        
        String title = model.getUrl();
        mainTabbedPane.addTab(title, panel);
        
        JPanel titlePanel = new JPanel();
        titlePanel.setOpaque(false);
        ((FlowLayout)titlePanel.getLayout()).setVgap(0);
        
        JLabel titleLabel = new JLabel("<html><b>"+model.getRequestMethod()+"</b> "+shortenTitle(title)+"</html>");
        titleLabel.setForeground(new Color(0, 136, 204));
        
        JButton tabBtn = new JButton(new javax.swing.ImageIcon(getClass().getResource("/com/cig/restca/img/glyphicon/small/glyphicons_192_circle_remove_smaller.png")));
        tabBtn.setMargin(new Insets(0,0,0,0));
        tabBtn.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                mainTabbedPane.remove(panel);
                System.gc();
            }
        });
        
        titlePanel.add(titleLabel);
        titlePanel.add(tabBtn);
        
        mainTabbedPane.setTabComponentAt(mainTabbedPane.getTabCount()-1, titlePanel);
        mainTabbedPane.setSelectedIndex(mainTabbedPane.getTabCount()-1);
        mainTabbedPane.setToolTipTextAt(mainTabbedPane.getTabCount()-1, "<html><b>"+model.getRequestMethod()+"</b> "+title+"</html>");
    }
    
    private String shortenTitle(String title) {
        String value=title;
        if(title.length()>50) {
            value = title.substring(0, 50);
        }
        return value;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        saveTbBtn = new javax.swing.JButton();
        openTbBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        getTbBtn = new javax.swing.JButton();
        postTbBtn = new javax.swing.JButton();
        putTbTn = new javax.swing.JButton();
        deleteTbBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        openBtn = new javax.swing.JButton();
        urlTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        getBtn = new javax.swing.JButton();
        postBtn = new javax.swing.JButton();
        putBTn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        mainTabbedPane = new javax.swing.JTabbedPane();
        progressBar = new javax.swing.JProgressBar();
        notifyLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        requestPropertiesBtn = new javax.swing.JButton();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        requestMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        systemMenu = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RESTful Client Application");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/cig/restca/img/glyphicon/restclientlogo.png")).getImage());
        setLocationByPlatform(true);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        saveTbBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cig/restca/img/glyphicon/white/glyphicons_443_floppy_disk.png"))); // NOI18N
        saveTbBtn.setFocusable(false);
        saveTbBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveTbBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(saveTbBtn);

        openTbBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cig/restca/img/glyphicon/white/glyphicons_144_folder_open.png"))); // NOI18N
        openTbBtn.setFocusable(false);
        openTbBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openTbBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(openTbBtn);
        jToolBar2.add(jSeparator3);

        getTbBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cig/restca/img/glyphicon/white/glyphicons_364_cloud_download.png"))); // NOI18N
        getTbBtn.setFocusable(false);
        getTbBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getTbBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(getTbBtn);

        postTbBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cig/restca/img/glyphicon/white/glyphicons_363_cloud_upload.png"))); // NOI18N
        postTbBtn.setFocusable(false);
        postTbBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        postTbBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(postTbBtn);

        putTbTn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cig/restca/img/glyphicon/white/glyphicons_150_edit.png"))); // NOI18N
        putTbTn.setFocusable(false);
        putTbTn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        putTbTn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(putTbTn);

        deleteTbBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cig/restca/img/glyphicon/white/glyphicons_016_bin.png"))); // NOI18N
        deleteTbBtn.setFocusable(false);
        deleteTbBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteTbBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(deleteTbBtn);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("URL"));

        openBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cig/restca/img/glyphicon/glyphicons_144_folder_open.png"))); // NOI18N
        openBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBtnActionPerformed(evt);
            }
        });

        urlTextField.setText("http://");
        urlTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                urlTextFieldFocusGained(evt);
            }
        });
        urlTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                urlTextFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(urlTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openBtn)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(openBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(urlTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("HTTP Requests"));

        getBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cig/restca/img/glyphicon/glyphicons_364_cloud_download.png"))); // NOI18N
        getBtn.setText("GET");
        getBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBtnActionPerformed(evt);
            }
        });

        postBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cig/restca/img/glyphicon/glyphicons_363_cloud_upload.png"))); // NOI18N
        postBtn.setText("POST");
        postBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postBtnActionPerformed(evt);
            }
        });

        putBTn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cig/restca/img/glyphicon/glyphicons_150_edit.png"))); // NOI18N
        putBTn.setText("PUT");
        putBTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                putBTnActionPerformed(evt);
            }
        });

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cig/restca/img/glyphicon/glyphicons_016_bin.png"))); // NOI18N
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(putBTn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBtn)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(postBtn)
                        .addComponent(getBtn))
                    .addComponent(putBTn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainTabbedPane.setPreferredSize(new java.awt.Dimension(800, 512));

        notifyLabel.setForeground(new java.awt.Color(51, 51, 51));
        notifyLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cig/restca/img/glyphicon/small/glyphicons_196_circle_exclamation_mark.png"))); // NOI18N
        notifyLabel.setText("System Ready");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Settings"));

        requestPropertiesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cig/restca/img/glyphicon/glyphicons_137_cogwheels.png"))); // NOI18N
        requestPropertiesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestPropertiesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(requestPropertiesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(requestPropertiesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        fileMenu.setText("File");
        mainMenuBar.add(fileMenu);

        requestMenu.setText("Request");

        jMenuItem1.setText("Get");
        requestMenu.add(jMenuItem1);

        jMenuItem2.setText("Post");
        requestMenu.add(jMenuItem2);

        jMenuItem3.setText("Put");
        requestMenu.add(jMenuItem3);

        jMenuItem4.setText("Delete");
        requestMenu.add(jMenuItem4);
        requestMenu.add(jSeparator1);

        jMenuItem5.setText("Head");
        requestMenu.add(jMenuItem5);

        mainMenuBar.add(requestMenu);

        jMenu2.setText("Settings");

        jMenuItem9.setText("Request Properties");
        jMenu2.add(jMenuItem9);

        mainMenuBar.add(jMenu2);

        systemMenu.setText("System");

        jMenuItem6.setText("About");
        systemMenu.add(jMenuItem6);

        jMenuItem7.setText("Manual");
        systemMenu.add(jMenuItem7);
        systemMenu.add(jSeparator2);

        jMenuItem8.setText("Help");
        systemMenu.add(jMenuItem8);

        mainMenuBar.add(systemMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(notifyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notifyLabel))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setProgress(boolean value, String msg) {
        progressBar.setIndeterminate(value);
        notifyLabel.setText(msg);
    }

    private void openBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openBtnActionPerformed

    private void getBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBtnActionPerformed
        String url = urlTextField.getText();
        clientController.executeGet(url);
    }//GEN-LAST:event_getBtnActionPerformed

    private void postBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postBtnActionPerformed
        clientController.executePost(urlTextField.getText());
    }//GEN-LAST:event_postBtnActionPerformed

    private void putBTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_putBTnActionPerformed

        new SwingWorker<Object, Object>() {

            @Override
            protected Object doInBackground() throws Exception {
                progressBar.setIndeterminate(true);
                String url = urlTextField.getText();
                clientController.executePut(urlTextField.getText());
                progressBar.setIndeterminate(false);
                return null;
            }
        }.execute();
    }//GEN-LAST:event_putBTnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        new SwingWorker<Object, Object>() {

            @Override
            protected Object doInBackground() throws Exception {
                progressBar.setIndeterminate(true);
                String url = urlTextField.getText();
                clientController.executeDelete(urlTextField.getText());
                progressBar.setIndeterminate(false);
                return null;
            }
        }.execute();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void requestPropertiesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestPropertiesBtnActionPerformed
        this.clientController.updateRequestProperties();
    }//GEN-LAST:event_requestPropertiesBtnActionPerformed

    private void urlTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_urlTextFieldFocusGained
        urlTextField.setSelectionStart(0);
        urlTextField.setSelectionEnd(urlTextField.getText().length());
    }//GEN-LAST:event_urlTextFieldFocusGained

    private void urlTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_urlTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.getBtnActionPerformed(null);
        }
    }//GEN-LAST:event_urlTextFieldKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteTbBtn;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton getBtn;
    private javax.swing.JButton getTbBtn;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JLabel notifyLabel;
    private javax.swing.JButton openBtn;
    private javax.swing.JButton openTbBtn;
    private javax.swing.JButton postBtn;
    private javax.swing.JButton postTbBtn;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton putBTn;
    private javax.swing.JButton putTbTn;
    private javax.swing.JMenu requestMenu;
    private javax.swing.JButton requestPropertiesBtn;
    private javax.swing.JButton saveTbBtn;
    private javax.swing.JMenu systemMenu;
    private javax.swing.JTextField urlTextField;
    // End of variables declaration//GEN-END:variables
}
